---
- name: Build employee app
  command: make -C {{ path_of_emplpoyee_app }}
  become_user: root

- name: change permissions of binaryfile
  file:
    path: /usr/local/employee/employee
    owner: root
    group: root
    mode: 744
