---
- name: Build salary app
  command: make -C {{ path_of_salary_app }}
  become_user: root

- name: change permissions of binaryfile
  file:
    path: /usr/local/salary/salary
    owner: root
    group: root
    mode: 744
