---
- name: add elastic search repo to apt
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name:
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: Installl ElasticSearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Start Elasticsearch
  systemd:
    name: elasticsearch
    state: started

- name: Change Elasticsearch password
  shell: |
    curl -XPUT -u elastic:changeme 'localhost:9200/_xpack/security/user/elastic/_password?pretty' -H 'Content-Type: application/json' -d'
    {
      "password": "elastic"
    }
    '